<?
require(PREFIJO_GENERAL."db/db.acudiente.php");
require(PREFIJO_GENERAL."db/db.evento.php");
require(PREFIJO_GENERAL."db/db.fullevents.php");
require(PREFIJO_GENERAL."db/db.fullmessages.php");
require(PREFIJO_GENERAL."db/db.fullnews.php");
require(PREFIJO_GENERAL."db/db.fullnotifications.php");
require(PREFIJO_GENERAL."db/db.grupo.php");
require(PREFIJO_GENERAL."db/db.institucion.php");
require(PREFIJO_GENERAL."db/db.mensaje.php");
require(PREFIJO_GENERAL."db/db.noticia.php");
require(PREFIJO_GENERAL."db/db.notificacion.php");
require(PREFIJO_GENERAL."db/db.plantilla.php");
require(PREFIJO_GENERAL."db/db.respuesta.php");
require(PREFIJO_GENERAL."db/db.revista.php");
require(PREFIJO_GENERAL."db/db.revistaXInstitucion.php");
require(PREFIJO_GENERAL."db/db.rol.php");
require(PREFIJO_GENERAL."db/db.tipoReceptor.php");
require(PREFIJO_GENERAL."db/db.usuario.php");
require(PREFIJO_GENERAL."db/db.usuarioXNotificacion.php");
?>
