<?
require(PREFIJO_GENERAL."db/db.acudiente.php");
require(PREFIJO_GENERAL."db/db.answersnews.php");
require(PREFIJO_GENERAL."db/db.evento.php");
require(PREFIJO_GENERAL."db/db.eventoXReceptor.php");
require(PREFIJO_GENERAL."db/db.events.php");
require(PREFIJO_GENERAL."db/db.grupo.php");
require(PREFIJO_GENERAL."db/db.institucion.php");
require(PREFIJO_GENERAL."db/db.mensaje.php");
require(PREFIJO_GENERAL."db/db.mensajeXReceptor.php");
require(PREFIJO_GENERAL."db/db.messages.php");
require(PREFIJO_GENERAL."db/db.news.php");
require(PREFIJO_GENERAL."db/db.noticia.php");
require(PREFIJO_GENERAL."db/db.noticiaXReceptor.php");
require(PREFIJO_GENERAL."db/db.noticiaXRespuesta.php");
require(PREFIJO_GENERAL."db/db.notificacion.php");
require(PREFIJO_GENERAL."db/db.plantilla.php");
require(PREFIJO_GENERAL."db/db.respuesta.php");
require(PREFIJO_GENERAL."db/db.revista.php");
require(PREFIJO_GENERAL."db/db.revistaXInstitucion.php");
require(PREFIJO_GENERAL."db/db.rol.php");
require(PREFIJO_GENERAL."db/db.sendersevents.php");
require(PREFIJO_GENERAL."db/db.sendersmessages.php");
require(PREFIJO_GENERAL."db/db.sendersnews.php");
require(PREFIJO_GENERAL."db/db.users.php");
require(PREFIJO_GENERAL."db/db.usuario.php");
require(PREFIJO_GENERAL."db/db.usuarioXNotificacion.php");
?>
